name: Bug report
description: Reportar un error o problema en el proyecto
title: "[BUG]: "
labels: [bug]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Descripción del problema
      description: Explica claramente el error o mejora que propones
      placeholder: Se cierra la app al pulsar en "X"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Explica cómo reproducir el error
      placeholder: |
        1. Ir a...
        2. Hacer click en...
        3. Observar el fallo
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Resultado esperado
      description: Qué debería ocurrir en lugar del error
      placeholder: El programa debería mostrar...
    validations:
      required: true
